INSERT INTO roles (role_name) VALUES
('SUPERVISOR'),
('DEVELOPER'),
('TESTER'),
('HR'),
('FINANCE'),
('MARKETING');

INSERT INTO users (name, email, role_id) VALUES
('Alice Johnson', 'alice.johnson@example.com', 1),
('Alicia Jones', 'alicia.jones@example.com', 1),
('Alison Smith', 'alison.smith@example.com', 1),
('Bob Brown', 'bob.brown@example.com', 2),
('Bobby White', 'bobby.white@example.com', 2),
('Robert Black', 'robert.black@example.com', 2),
('Charlie Green', 'charlie.green@example.com', 3),
('Charles Grey', 'charles.grey@example.com', 3),
('Charlotte Blue', 'charlotte.blue@example.com', 3),
('David Clark', 'david.clark@example.com', 4),
('Dave Clarke', 'dave.clarke@example.com', 4),
('Daniel Cook', 'daniel.cook@example.com', 4),
('Eve Adams', 'eve.adams@example.com', 5),
('Eva Saunders', 'eva.saunders@example.com', 5),
('Evelyn Lee', 'evelyn.lee@example.com', 5),
('Frank Harris', 'frank.harris@example.com', 6),
('Francis Harris', 'francis.harris@example.com', 6),
('Frankie Harris', 'frankie.harris@example.com', 6),
('Grace Kelly', 'grace.kelly@example.com', 1),
('Gracie King', 'gracie.king@example.com', 1),
('Hannah Scott', 'hannah.scott@example.com', 2),
('Anna Scott', 'anna.scott@example.com', 2),
('Ian Walker', 'ian.walker@example.com', 3),
('Iain Walker', 'iain.walker@example.com', 3),
('Jack Turner', 'jack.turner@example.com', 4),
('Jackson Turner', 'jackson.turner@example.com', 4),
('Jill Collins', 'jill.collins@example.com', 5),
('Julia Collins', 'julia.collins@example.com', 5),
('John Smith', 'john.smith@example.com', 6),
('Johnny Smith', 'johnny.smith@example.com', 6),
('Jonathan Smith', 'jonathan.smith@example.com', 6),
('Karen Lewis', 'karen.lewis@example.com', 1),
('Kara Lewis', 'kara.lewis@example.com', 1),
('Leo Martin', 'leo.martin@example.com', 2),
('Leon Martin', 'leon.martin@example.com', 2),
('Liam Martin', 'liam.martin@example.com', 2),
('Mia Walker', 'mia.walker@example.com', 3),
('Mya Walker', 'mya.walker@example.com', 3),
('Noah Adams', 'noah.adams@example.com', 4),
('Noe Adams', 'noe.adams@example.com', 4),
('Olivia Brown', 'olivia.brown@example.com', 5),
('Ollie Brown', 'ollie.brown@example.com', 5),
('Paul King', 'paul.king@example.com', 6),
('Paula King', 'paula.king@example.com', 6),
('Quinn Harris', 'quinn.harris@example.com', 1),
('Quincy Harris', 'quincy.harris@example.com', 1),
('Rachel White', 'rachel.white@example.com', 2),
('Rachael White', 'rachael.white@example.com', 2),
('Samuel Lee', 'samuel.lee@example.com', 3),
('Sam Lee', 'sam.lee@example.com', 3),
('Sophia Green', 'sophia.green@example.com', 4),
('Sophie Green', 'sophie.green@example.com', 4),
('Thomas Clark', 'thomas.clark@example.com', 5),
('Tom Clark', 'tom.clark@example.com', 5),
('Uma Scott', 'uma.scott@example.com', 6),
('Umar Scott', 'umar.scott@example.com', 6),
('Victor Brown', 'victor.brown@example.com', 1),
('Viktor Brown', 'viktor.brown@example.com', 1),
('William Jones', 'william.jones@example.com', 2),
('Will Jones', 'will.jones@example.com', 2),
('Wendy Lewis', 'wendy.lewis@example.com', 3),
('Wanda Lewis', 'wanda.lewis@example.com', 3),
('Xander King', 'xander.king@example.com', 4),
('Alexander King', 'alexander.king@example.com', 4),
('Yara Collins', 'yara.collins@example.com', 5),
('Yvonne Collins', 'yvonne.collins@example.com', 5),
('Zachary Smith', 'zachary.smith@example.com', 6),
('Zack Smith', 'zack.smith@example.com', 6);
